In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [2]:
with open('C:/Users/Lenovo/Downloads/archive (13)/poems.txt','r', encoding='utf-8')as story:
  story_data = story.read()

In [3]:
story_data

'I have wished a bird would fly away,\nAnd not sing by my house all day;\n\nHave clapped my hands at him from the door\nWhen it seemed as if I could bear no more.\n\nThe fault must partly have been in me.\nThe bird was not to blame for his key.\n\nAnd of course there must be something wrong\nIn wanting to silence any song.\n\nHe halted in the wind, and — what was that\nFar in the maples, pale, but not a ghost?\nHe stood there bringing March against his thought,\nAnd yet too ready to believe the most.\n\n"Oh, that\'s the Paradise-in-bloom," I said;\nAnd truly it was fair enough for flowers\nhad we but in us to assume in march\nSuch white luxuriance of May for ours.\n\nWe stood a moment so in a strange world,\nMyself as one his own pretense deceives;\nAnd then I said the truth (and we moved on).\nA young beech clinging to its last year\'s leaves.\n\nThe farmhouse lingers, though averse to square\nWith the new city street it has to wear\nA number in. But what about the brook\nThat held th

In [4]:
import re                             
def clean_text(text):
  text = re.sub(r',', '', text)
  text = re.sub(r'\'', '',  text)
  text = re.sub(r'\"', '', text)
  text = re.sub(r'\(', '', text)
  text = re.sub(r'\)', '', text)
  text = re.sub(r'\n', '', text)
  text = re.sub(r'“', '', text)
  text = re.sub(r'”', '', text)
  text = re.sub(r'’', '', text)
  text = re.sub(r'\.', '', text)
  text = re.sub(r';', '', text)
  text = re.sub(r':', '', text)
  text = re.sub(r'\-', '', text)

  return text

In [5]:
lower_data = story_data.lower()           

split_data = lower_data.splitlines()

In [6]:
lower_data

'i have wished a bird would fly away,\nand not sing by my house all day;\n\nhave clapped my hands at him from the door\nwhen it seemed as if i could bear no more.\n\nthe fault must partly have been in me.\nthe bird was not to blame for his key.\n\nand of course there must be something wrong\nin wanting to silence any song.\n\nhe halted in the wind, and — what was that\nfar in the maples, pale, but not a ghost?\nhe stood there bringing march against his thought,\nand yet too ready to believe the most.\n\n"oh, that\'s the paradise-in-bloom," i said;\nand truly it was fair enough for flowers\nhad we but in us to assume in march\nsuch white luxuriance of may for ours.\n\nwe stood a moment so in a strange world,\nmyself as one his own pretense deceives;\nand then i said the truth (and we moved on).\na young beech clinging to its last year\'s leaves.\n\nthe farmhouse lingers, though averse to square\nwith the new city street it has to wear\na number in. but what about the brook\nthat held th

In [7]:
split_data

['i have wished a bird would fly away,',
 'and not sing by my house all day;',
 '',
 'have clapped my hands at him from the door',
 'when it seemed as if i could bear no more.',
 '',
 'the fault must partly have been in me.',
 'the bird was not to blame for his key.',
 '',
 'and of course there must be something wrong',
 'in wanting to silence any song.',
 '',
 'he halted in the wind, and — what was that',
 'far in the maples, pale, but not a ghost?',
 'he stood there bringing march against his thought,',
 'and yet too ready to believe the most.',
 '',
 '"oh, that\'s the paradise-in-bloom," i said;',
 'and truly it was fair enough for flowers',
 'had we but in us to assume in march',
 'such white luxuriance of may for ours.',
 '',
 'we stood a moment so in a strange world,',
 'myself as one his own pretense deceives;',
 'and then i said the truth (and we moved on).',
 "a young beech clinging to its last year's leaves.",
 '',
 'the farmhouse lingers, though averse to square',
 'with the

In [8]:
final = ''                               
for line in split_data:
  line = clean_text(line)
  final += '\n' + line

In [9]:
final

'\ni have wished a bird would fly away\nand not sing by my house all day\n\nhave clapped my hands at him from the door\nwhen it seemed as if i could bear no more\n\nthe fault must partly have been in me\nthe bird was not to blame for his key\n\nand of course there must be something wrong\nin wanting to silence any song\n\nhe halted in the wind and — what was that\nfar in the maples pale but not a ghost?\nhe stood there bringing march against his thought\nand yet too ready to believe the most\n\noh thats the paradiseinbloom i said\nand truly it was fair enough for flowers\nhad we but in us to assume in march\nsuch white luxuriance of may for ours\n\nwe stood a moment so in a strange world\nmyself as one his own pretense deceives\nand then i said the truth and we moved on\na young beech clinging to its last years leaves\n\nthe farmhouse lingers though averse to square\nwith the new city street it has to wear\na number in but what about the brook\nthat held the house as in an elbowcrook?\

In [10]:
final_data = final.split('\n') 

In [11]:
final_data

['',
 'i have wished a bird would fly away',
 'and not sing by my house all day',
 '',
 'have clapped my hands at him from the door',
 'when it seemed as if i could bear no more',
 '',
 'the fault must partly have been in me',
 'the bird was not to blame for his key',
 '',
 'and of course there must be something wrong',
 'in wanting to silence any song',
 '',
 'he halted in the wind and — what was that',
 'far in the maples pale but not a ghost?',
 'he stood there bringing march against his thought',
 'and yet too ready to believe the most',
 '',
 'oh thats the paradiseinbloom i said',
 'and truly it was fair enough for flowers',
 'had we but in us to assume in march',
 'such white luxuriance of may for ours',
 '',
 'we stood a moment so in a strange world',
 'myself as one his own pretense deceives',
 'and then i said the truth and we moved on',
 'a young beech clinging to its last years leaves',
 '',
 'the farmhouse lingers though averse to square',
 'with the new city street it has 

In [12]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Instantiating the Tokenizer
max_vocab = 1000000
tokenizer = Tokenizer(num_words=max_vocab)
tokenizer.fit_on_texts(final_data)

# Getting the total number of words of the data.
word2idx = tokenizer.word_index
print(len(word2idx))
print(word2idx)
vocab_size = len(word2idx) + 1        # Adding 1 to the vocab_size because the index starts from 1 not 0. This will make it uniform when using it further
print(vocab_size)

3057
{'the': 1, 'and': 2, 'to': 3, 'of': 4, 'a': 5, 'i': 6, 'in': 7, 'that': 8, 'it': 9, 'with': 10, 'is': 11, 'all': 12, 'as': 13, 'was': 14, 'for': 15, 'not': 16, 'my': 17, 'you': 18, 'be': 19, 'from': 20, 'he': 21, 'but': 22, 'on': 23, 'they': 24, 'have': 25, 'we': 26, 'or': 27, 'his': 28, 'by': 29, 'me': 30, 'are': 31, 'one': 32, 'at': 33, 'its': 34, 'when': 35, 'so': 36, 'this': 37, 'them': 38, 'her': 39, 'like': 40, 'she': 41, 'if': 42, 'our': 43, 'what': 44, 'where': 45, 'there': 46, 'no': 47, 'some': 48, 'which': 49, 'had': 50, 'their': 51, 'more': 52, 'will': 53, 'out': 54, 'then': 55, 'know': 56, 'now': 57, 'thy': 58, 'too': 59, 'see': 60, 'thou': 61, 'day': 62, 'yet': 63, 'would': 64, 'us': 65, 'who': 66, 'come': 67, 'nor': 68, 'could': 69, 'may': 70, 'been': 71, 'down': 72, 'up': 73, 'love': 74, 'away': 75, 'thought': 76, 'said': 77, 'an': 78, 'how': 79, 'here': 80, 'do': 81, 'can': 82, 'such': 83, 'years': 84, 'though': 85, 'than': 86, 'were': 87, 'go': 88, 'your': 89, 'le

In [13]:
input_seq = []

for line in final_data:
  token_list = tokenizer.texts_to_sequences([line])[0]
  for i in range(1, len(token_list)):
    n_gram_seq = token_list[:i+1]
    input_seq.append(n_gram_seq)


In [14]:
input_seq

[[6, 25],
 [6, 25, 1168],
 [6, 25, 1168, 5],
 [6, 25, 1168, 5, 234],
 [6, 25, 1168, 5, 234, 64],
 [6, 25, 1168, 5, 234, 64, 303],
 [6, 25, 1168, 5, 234, 64, 303, 75],
 [2, 16],
 [2, 16, 262],
 [2, 16, 262, 29],
 [2, 16, 262, 29, 17],
 [2, 16, 262, 29, 17, 172],
 [2, 16, 262, 29, 17, 172, 12],
 [2, 16, 262, 29, 17, 172, 12, 62],
 [25, 1169],
 [25, 1169, 17],
 [25, 1169, 17, 536],
 [25, 1169, 17, 536, 33],
 [25, 1169, 17, 536, 33, 109],
 [25, 1169, 17, 536, 33, 109, 20],
 [25, 1169, 17, 536, 33, 109, 20, 1],
 [25, 1169, 17, 536, 33, 109, 20, 1, 263],
 [35, 9],
 [35, 9, 304],
 [35, 9, 304, 13],
 [35, 9, 304, 13, 42],
 [35, 9, 304, 13, 42, 6],
 [35, 9, 304, 13, 42, 6, 69],
 [35, 9, 304, 13, 42, 6, 69, 723],
 [35, 9, 304, 13, 42, 6, 69, 723, 47],
 [35, 9, 304, 13, 42, 6, 69, 723, 47, 52],
 [1, 1170],
 [1, 1170, 110],
 [1, 1170, 110, 1171],
 [1, 1170, 110, 1171, 25],
 [1, 1170, 110, 1171, 25, 71],
 [1, 1170, 110, 1171, 25, 71, 7],
 [1, 1170, 110, 1171, 25, 71, 7, 30],
 [1, 234],
 [1, 234, 14

In [15]:
max_seq_length = max(len(x) for x in input_seq)
print(max_seq_length)

62


In [16]:
input_seq = np.array(pad_sequences(input_seq, maxlen=max_seq_length, padding='pre'))

In [17]:
input_seq

array([[   0,    0,    0, ...,    0,    6,   25],
       [   0,    0,    0, ...,    6,   25, 1168],
       [   0,    0,    0, ...,   25, 1168,    5],
       ...,
       [   0,    0,    0, ...,   77, 3057,   26],
       [   0,    0,    0, ..., 3057,   26,   31],
       [   0,    0,    0, ...,   26,   31,  351]])

In [18]:
xs = input_seq[:, :-1]        # xs contains every word in sentence except the last one because we are using this value to predict the y value
labels = input_seq[:, -1]     # labels contains only the last word of the sentence which will help in hot encoding the y value in next step
print("xs: ",xs)
print("labels:",labels)
from numpy import save
save('data.npy', labels)

xs:  [[   0    0    0 ...    0    0    6]
 [   0    0    0 ...    0    6   25]
 [   0    0    0 ...    6   25 1168]
 ...
 [   0    0    0 ...    2   77 3057]
 [   0    0    0 ...   77 3057   26]
 [   0    0    0 ... 3057   26   31]]
labels: [  25 1168    5 ...   26   31  351]


In [19]:
from tensorflow.keras.utils import to_categorical

ys = to_categorical(labels, num_classes=vocab_size)
print(ys)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [20]:
from tensorflow.keras.layers import Input, Dense, Embedding, LSTM, Dropout, Bidirectional, GlobalMaxPooling1D
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Sequential

# using the functional APIs of keras to define the model

i = Input(shape=(max_seq_length - 1, ))                         
x = Embedding(vocab_size, 124)(i)
x = Dropout(0.2)(x)
x = LSTM(520, return_sequences=True)(x)
x = Bidirectional(layer=LSTM(340, return_sequences=True))(x)
x = GlobalMaxPooling1D()(x)
x = Dense(1024, activation='relu')(x)
x = Dense(vocab_size, activation='softmax')(x)

model = Model(i,x)

In [21]:
model.compile(optimizer=Adam(lr=0.001),
              loss = 'categorical_crossentropy',
              metrics=['accuracy'])

model.summary()                                       # We can know about the shape of the model

r = model.fit(xs,ys,epochs=5)

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 61)]              0         
                                                                 
 embedding (Embedding)       (None, 61, 124)           379192    
                                                                 
 dropout (Dropout)           (None, 61, 124)           0         
                                                                 
 lstm (LSTM)                 (None, 61, 520)           1341600   
                                                                 
 bidirectional (Bidirection  (None, 61, 680)           2341920   
 al)                                                             
                                                                 
 global_max_pooling1d (Glob  (None, 680)               0         
 alMaxPooling1D)                                             

376/376 [==============================] - 613s 2s/step - loss: 6.8890 - accuracy: 0.0490
Epoch 2/5
376/376 [==============================] - 586s 2s/step - loss: 6.5179 - accuracy: 0.0506
Epoch 3/5
376/376 [==============================] - 629s 2s/step - loss: 6.3198 - accuracy: 0.0535
Epoch 4/5
376/376 [==============================] - 593s 2s/step - loss: 6.1463 - accuracy: 0.0603
Epoch 5/5
376/376 [==============================] - 605s 2s/step - loss: 5.9927 - accuracy: 0.0634


In [22]:

def predict_words(seed, no_words):
  for i in range(no_words):
    token_list = tokenizer.texts_to_sequences([seed])[0]
    token_list = pad_sequences([token_list], maxlen=max_seq_length-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=1)

    new_word = ''

    for word, index in tokenizer.word_index.items():
      if predicted == index:
        new_word = word
        break
    seed += " " + new_word
  print(seed)

In [23]:
seed_text = 'sun and moon'
next_words = 10

predict_words(seed_text, next_words)

1/1 [==============================] - 0s 124ms/step
sun and moon the heart of the heart of the heart of the
